Repository BinaryStudioAcademy/bsa-2022-easymeets, pull requests merged in 2022-08, with the labels that each got.

#8 Feature/database scheme
  README.md
Labels: database

#15 General menu item for new availability slot added
  frontend/src/app/app.module.ts
  frontend/src/app/core/models/IGeneralAvailabilitySettings.ts
  frontend/src/app/modules/availability/availability.module.ts
  frontend/src/app/modules/availability/new-slot/general/general.component.html
  frontend/src/app/modules/availability/new-slot/general/general.component.sass
  frontend/src/app/modules/availability/new-slot/general/general.component.ts
  frontend/src/app/shared/material/material.module.ts
  frontend/src/app/shared/styles/common-page-styles.sass
Labels: frontend

#17 Feature/header template
  frontend/src/app/modules/header/header-item/header-item.component.html
  frontend/src/app/modules/header/header-item/header-item.component.sass
  frontend/src/app/modules/header/header-item/header-item.component.ts
  frontend/src/app/modules/header/header.module.ts
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/modules/main/main.module.ts
  frontend/src/app/shared/material/material.module.ts
  frontend/src/app/shared/styles/common-page-styles.sass
  frontend/src/assets/header/header-ava-template.png
  frontend/src/assets/header/header-logo.png
  frontend/src/assets/header/header-pop-up.png
  frontend/src/assets/header/header-pop-up__account.png
  frontend/src/assets/header/header-pop-up__integrations.png
  frontend/src/assets/header/header-pop-up__logout.png
  frontend/src/assets/header/header-pop-up__plus.png
  frontend/src/assets/header/header-pop-up__team.png
  frontend/src/styles/color-variables.sass
  frontend/src/styles/index.sass
  frontend/src/styles/material.sass
  frontend/src/styles/theme.sass
Labels: enhancement

#44 Entities and existing dtos validation implemented
  backend/EasyMeets.Core/EasyMeets.Core.Common/Validation/ValidationExtensions.cs
  backend/EasyMeets.Core/EasyMeets.Core.DAL/Entities/AdvancedSlotSettings.cs
  backend/EasyMeets.Core/EasyMeets.Core.DAL/Entities/AvailabilitySlot.cs
  backend/EasyMeets.Core/EasyMeets.Core.DAL/Entities/ExternalAttendee.cs
  backend/EasyMeets.Core/EasyMeets.Core.DAL/Entities/Location.cs
  backend/EasyMeets.Core/EasyMeets.Core.DAL/Entities/Team.cs
  backend/EasyMeets.Core/EasyMeets.Core.DAL/Entities/User.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Validators/Availability/NewAvailability/EventDetailsDtoValidator.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Validators/Availability/NewAvailability/GeneralDetailsDtoValidator.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Validators/Availability/NewAvailability/NewAdvancedSlotSettingsDtoValidator.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Validators/User/UserDtoValidator.cs
Labels: enhancement, backend

#51 Feature/external booking
  frontend/src/app/app-routing.module.ts
  frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.html
  frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.sass
  frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.ts
  frontend/src/app/modules/external-booking/external-booking-routing.module.ts
  frontend/src/app/modules/external-booking/external-booking.module.ts
Labels: enhancement, frontend

#57 Bug/delete main
  frontend/src/app/app-routing.module.ts
  frontend/src/app/modules/main/main-page/main-page.component.html
  frontend/src/app/modules/main/main-page/main-page.component.sass
  frontend/src/app/modules/main/main-page/main-page.component.ts
  frontend/src/app/modules/main/main-routing.module.ts
  frontend/src/app/modules/main/main.module.ts
Labels: bug, frontend

#59 Bug/fix general settings page
  frontend/src/app/modules/availability/new-slot/general/general.component.sass
  frontend/src/app/modules/availability/new-slot/new-availability/new-availability.component.html
  frontend/src/app/modules/availability/new-slot/new-availability/new-availability.component.sass
  frontend/src/app/shared/styles/common-page-styles.sass
Labels: bug

#61 fixed ability to delete slot on availability page
  frontend/src/app/modules/availability/availability-page/availability-page.component.html
  frontend/src/app/modules/availability/availability-page/availability-page.component.ts
  frontend/src/app/modules/availability/slot/slot.component.ts
  frontend/src/app/modules/availability/team/team.component.html
  frontend/src/app/modules/availability/team/team.component.ts
  frontend/src/app/modules/availability/user-slot/user-slot.component.html
  frontend/src/app/modules/availability/user-slot/user-slot.component.ts
Labels: bug

#66 enhancement for user profile on the backend
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Interfaces/IUserService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/UserService.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/UserController.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Program.cs
Labels: enhancement, backend

#83 changed migration
  backend/EasyMeets.Core/EasyMeets.Core.DAL/Migrations/20220818154322_ChangeTimeZoneToInt.Designer.cs
  backend/EasyMeets.Core/EasyMeets.Core.DAL/Migrations/20220818154322_ChangeTimeZoneToInt.cs
  backend/EasyMeets.Core/EasyMeets.Core.DAL/Migrations/EasyMeetsCoreContextModelSnapshot.cs
Labels: bug

#89 Add allow anonymous
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/UserController.cs
Labels: bug, backend

#94 Fixed avatar image problem in header
  frontend/src/app/modules/header/header-item/header-item.component.html
  frontend/src/app/modules/header/header-item/header-item.component.sass
  frontend/src/assets/header/avatar-icon.png
  frontend/src/assets/header/header-ava-template.png
  frontend/src/styles/color-variables.sass
Labels: bug, frontend

#104 Card #106 Bug/unclickable update preference
  frontend/src/app/modules/user/user-profile-page/user-profile-page.component.ts
Labels: bug, frontend

#98 Card #96 Add watcher service
  backend/EasyMeets.All.sln
  backend/EasyMeets.Watcher.sln
  backend/EasyMeets.Watcher/Dockerfile
  backend/EasyMeets.Watcher/EasyMeets.Watcher.BLL/Commands/InsertValueCommand.cs
  backend/EasyMeets.Watcher/EasyMeets.Watcher.BLL/EasyMeets.Watcher.BLL.csproj
  backend/EasyMeets.Watcher/EasyMeets.Watcher.BLL/EasyMeetsWatcherBLLEntrypoint.cs
  backend/EasyMeets.Watcher/EasyMeets.Watcher.BLL/Handlers/GetExampleTextListHandler.cs
  backend/EasyMeets.Watcher/EasyMeets.Watcher.BLL/Handlers/InsertValueHandler.cs
  backend/EasyMeets.Watcher/EasyMeets.Watcher.BLL/Queries/GetExampleTextListQuery.cs
  backend/EasyMeets.Watcher/EasyMeets.Watcher.WebAPI/Controllers/ExampleController.cs
  backend/EasyMeets.Watcher/EasyMeets.Watcher.WebAPI/EasyMeets.Watcher.WebAPI.csproj
  backend/EasyMeets.Watcher/EasyMeets.Watcher.WebAPI/Program.cs
  backend/EasyMeets.Watcher/EasyMeets.Watcher.WebAPI/Properties/launchSettings.json
  backend/EasyMeets.Watcher/EasyMeets.Watcher.WebAPI/appsettings.Development.json
  backend/EasyMeets.Watcher/EasyMeets.Watcher.WebAPI/appsettings.json
  docker-compose.apps.prod.yml
  docker-compose.apps.yml
Labels: enhancement, backend

#112 Rename date format enum, add label mappings to enums from user profile page settings
  backend/EasyMeets.Core/EasyMeets.Core.Common/Enums/DateFormat.cs
  frontend/src/app/core/helpers/country-label-mapping.ts
  frontend/src/app/core/helpers/countryCode.ts
  frontend/src/app/core/helpers/date-format-label-mapping.ts
  frontend/src/app/core/helpers/language-label-mapping.ts
  frontend/src/app/core/helpers/time-format-label-mapping.ts
  frontend/src/app/modules/auth/components/sign-up-form/sign-up-form.component.ts
  frontend/src/app/modules/settings/user/user-profile-page/user-profile-page.component.html
  frontend/src/app/modules/settings/user/user-profile-page/user-profile-page.component.ts
  frontend/src/app/shared/enums/countryCode.ts
  frontend/src/app/shared/enums/dateFormat.ts
Labels: bug, frontend

#107 Feature/external booking time #75
  frontend/src/app/core/helpers/external-booking-time-slots-helper.ts
  frontend/src/app/core/models/ICalendarWeek.ts
  frontend/src/app/core/models/IDayTimeSlot.ts
  frontend/src/app/core/models/IExtendBookingSideMenu.ts
  frontend/src/app/modules/external-booking/external-booking-choose-meeting-page/external-booking-choose-meeting-page.component.html
  frontend/src/app/modules/external-booking/external-booking-choose-meeting-page/external-booking-choose-meeting-page.component.sass
  frontend/src/app/modules/external-booking/external-booking-choose-meeting-page/external-booking-choose-meeting-page.component.ts
  frontend/src/app/modules/external-booking/external-booking-choose-time-page/external-booking-choose-time-page.component.html
  frontend/src/app/modules/external-booking/external-booking-choose-time-page/external-booking-choose-time-page.component.sass
  frontend/src/app/modules/external-booking/external-booking-choose-time-page/external-booking-choose-time-page.component.ts
  frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.html
  frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.sass
  frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.ts
  frontend/src/app/modules/external-booking/external-booking-routing.module.ts
  frontend/src/app/modules/external-booking/external-booking.module.ts
  frontend/src/styles/material.sass
Labels: enhancement

#127 Add min-height to card options #116
  frontend/src/app/modules/availability/slot/slot.component.sass
Labels: bug

#133 Add time-options max-width and text-overflow #126
  frontend/src/app/modules/availability/slot/slot.component.sass
Labels: bug

#132 #125 Any photo should take the form of a circle
  frontend/src/app/modules/settings/user/user-profile-page/user-profile-page.component.sass
Labels: enhancement

#109 Card #104 fix bug by adding loader and removing email async validator
  frontend/src/app/modules/auth/components/sign-in-form/sign-in-form.component.html
  frontend/src/app/modules/auth/components/sign-in-form/sign-in-form.component.ts
  frontend/src/app/modules/auth/components/sign-up-form/sign-up-form.component.ts
Labels: bug, frontend

#143 Card # 104 Fix acces token update after sign in and email verification status
  frontend/src/app/core/services/auth.service.ts
Labels: bug, frontend

#140 Return select border in external-booking-time #140
  frontend/src/app/modules/external-booking/external-booking-choose-time-page/external-booking-choose-time-page.component.html
  frontend/src/app/modules/external-booking/external-booking-choose-time-page/external-booking-choose-time-page.component.sass
Labels: bug

#139 Feature/notification emails page #113
  frontend/src/app/core/helpers/new-availability-menu-helper.ts
  frontend/src/app/core/models/IAvailiabilitySlot.ts
  frontend/src/app/core/models/save-availability-slot/ISaveConfirmationEmailDetails.ts
  frontend/src/app/modules/availability/availability.module.ts
  frontend/src/app/modules/availability/new-slot/new-availability/new-availability.component.html
  frontend/src/app/modules/availability/new-slot/new-availability/new-availability.component.ts
  frontend/src/app/modules/availability/new-slot/notification-emails/notification-emails.component.html
  frontend/src/app/modules/availability/new-slot/notification-emails/notification-emails.component.sass
  frontend/src/app/modules/availability/new-slot/notification-emails/notification-emails.component.ts
Labels: enhancement

#156 Feature/multiple team members #134
  frontend/src/app/core/helpers/slot-with-members-multiple-helper.ts
  frontend/src/app/core/models/IAvailabilitySlotMember.ts
  frontend/src/app/core/models/IExtendBookingSideMenu.ts
  frontend/src/app/modules/external-booking/external-booking-choose-members-page/external-booking-choose-members-page.component.html
  frontend/src/app/modules/external-booking/external-booking-choose-members-page/external-booking-choose-members-page.component.sass
  frontend/src/app/modules/external-booking/external-booking-choose-members-page/external-booking-choose-members-page.component.ts
  frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.html
  frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.sass
  frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.ts
  frontend/src/app/modules/external-booking/external-booking-routing.module.ts
  frontend/src/app/modules/external-booking/external-booking.module.ts
Labels: enhancement

#157 # 19 Fixed. User allowed to sign up with mismatched password
  frontend/src/app/modules/auth/components/sign-up-form/sign-up-form.component.html
  frontend/src/app/modules/auth/components/sign-up-form/sign-up-form.component.ts
  frontend/src/app/modules/auth/validators/passwordsErrorStateMatcher.ts
Labels: bug, frontend

#159 Bug/header avatar #160
  frontend/src/app/modules/header/header-item/header-item.component.html
  frontend/src/app/modules/header/header-item/header-item.component.sass
  frontend/src/app/modules/header/header-item/header-item.component.ts
Labels: bug

#164 Feature/inactive slot confirmation #145
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Interfaces/IAvailabilityService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/AvailabilityService.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/AvailabilityController.cs
  frontend/src/app/core/services/availability-slot.service.ts
  frontend/src/app/modules/availability/slot/slot.component.html
  frontend/src/app/modules/availability/slot/slot.component.ts
  frontend/src/app/modules/availability/team/team.component.html
  frontend/src/app/modules/availability/team/team.component.ts
  frontend/src/app/modules/availability/user-slot/user-slot.component.html
  frontend/src/app/modules/availability/user-slot/user-slot.component.ts
  frontend/src/app/shared/constants/shared-messages.ts
Labels: enhancement

#165 Card #112 Team-select
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Interfaces/IAvailabilityService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Interfaces/IMeetingService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Interfaces/ITeamService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/MappingProfiles/TeamProfile.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/AvailabilityService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/MeetingService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/TeamService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/UploadFileService.cs
  backend/EasyMeets.Core/EasyMeets.Core.Common/DTO/Team/UpdateTeamDto.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/AvailabilityController.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/MeetingController.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/TeamController.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/appsettings.json
  frontend/src/app/core/enums/team-state-change-action.enum.ts
  frontend/src/app/core/helpers/teams-helper.ts
  frontend/src/app/core/helpers/user-settings-menu-helper.ts
  frontend/src/app/core/interfaces/sideMenu/sideMenuGroup.ts
  frontend/src/app/core/services/availability-slot.service.ts
  frontend/src/app/core/services/meeting-bookings.service.ts
  frontend/src/app/core/services/team.service.ts
  frontend/src/app/modules/availability/availability-page/availability-page.component.ts
  frontend/src/app/modules/availability/new-slot/new-availability-page/new-availability-page.component.ts
  frontend/src/app/modules/bookings/bookers-page/bookers-page.component.ts
  frontend/src/app/modules/bookings/bookings-page/bookings-page.component.ts
  frontend/src/app/modules/header/header-item/header-item.component.html
  frontend/src/app/modules/header/header-item/header-item.component.ts
  frontend/src/app/modules/settings/settings-page/settings-page.component.ts
  frontend/src/app/modules/settings/team/edit-team/edit-team.component.html
  frontend/src/app/modules/settings/team/edit-team/edit-team.component.sass
  frontend/src/app/modules/settings/team/edit-team/edit-team.component.ts
  frontend/src/app/modules/settings/team/new-team/new-team.component.html
  frontend/src/app/modules/settings/team/new-team/new-team.component.sass
  frontend/src/app/modules/settings/team/new-team/new-team.component.ts
  frontend/src/app/modules/settings/team/team-preferences/team-preferences.component.html
  frontend/src/app/modules/settings/team/team-preferences/team-preferences.component.ts
  frontend/src/app/modules/settings/team/team-routing.module.ts
  frontend/src/app/modules/settings/team/team.module.ts
  frontend/src/app/modules/side-menu/menu/side-menu.component.html
  frontend/src/app/modules/side-menu/menu/side-menu.component.sass
Labels: enhancement, frontend, backend

#177 Feature/availability slot new design #167
  frontend/src/app/modules/availability/availability-page/availability-page.component.sass
  frontend/src/app/modules/availability/slot/slot.component.html
  frontend/src/app/modules/availability/slot/slot.component.sass
  frontend/src/app/modules/availability/team/team.component.sass
  frontend/src/app/modules/availability/user-slot/user-slot.component.sass
  frontend/src/app/modules/settings/user/user-profile-page/user-profile-page.component.ts
  frontend/src/styles/color-variables.sass
  frontend/src/styles/material.sass
Labels: frontend

#182 Bug/default avatar availability page #176
  frontend/src/app/modules/availability/user-slot/user-slot.component.html
  frontend/src/assets/header/avatar-icon.png
Labels: bug

#185 Bug/inactive slot requirements #145
  frontend/src/app/shared/constants/shared-messages.ts
Labels: bug

#188 [#179] fixed new availability slot bug
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Interfaces/ITeamService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Interfaces/ITeamSharedService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/TeamService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/TeamSharedService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/UserService.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/TeamController.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
Labels: bug, backend

#166 #93 Add new meeting page
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Interfaces/IMeetingService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Interfaces/ITeamService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/MappingProfiles/MeetingMemberProfile.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/MappingProfiles/MeetingProfile.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/MappingProfiles/TeamMemberProfile.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/MappingProfiles/TeamProfile.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/MappingProfiles/UserProfile.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/MeetingService.cs
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/TeamService.cs
  backend/EasyMeets.Core/EasyMeets.Core.Common/DTO/Meeting/SaveNewMeetingDto.cs
  backend/EasyMeets.Core/EasyMeets.Core.Common/DTO/Team/NewMeetingTeamMemberDto.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/MeetingController.cs
  backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
  frontend/src/app/app-routing.module.ts
  frontend/src/app/app.module.ts
  frontend/src/app/core/helpers/display-duration-hepler.ts
  frontend/src/app/core/helpers/location-type-label-mapping.ts
  frontend/src/app/core/helpers/slot-with-members-multiple-helper.ts
  frontend/src/app/core/models/IAvailabilitySlot.ts
  frontend/src/app/core/models/IDuration.ts
  frontend/src/app/core/models/IExtendBookingSideMenu.ts
  frontend/src/app/core/models/INewMeeting.ts
  frontend/src/app/core/models/INewMeetingTeamMember.ts
  frontend/src/app/core/models/locationType.ts
  frontend/src/app/core/models/save-availability-slot/ISaveGeneralSettings.ts
  frontend/src/app/core/services/new-meeting.service.ts
  frontend/src/app/modules/availability/availability-page/availability-page.component.html
  frontend/src/app/modules/availability/new-slot/general/general.component.html
  frontend/src/app/modules/availability/new-slot/general/general.component.ts
  frontend/src/app/modules/availability/slot/slot.component.ts
  frontend/src/app/modules/external-booking/external-booking-choose-meeting-page/external-booking-choose-meeting-page.component.html
  frontend/src/app/modules/external-booking/external-booking-choose-meeting-page/external-booking-choose-meeting-page.component.ts
  frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.html
  frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.ts
  frontend/src/app/modules/header/header-item/header-item.component.sass
  frontend/src/app/modules/new-meeting/new-meeting-routing.module.ts
  frontend/src/app/modules/new-meeting/new-meeting.module.ts
  frontend/src/app/modules/new-meeting/new-meeting/new-meeting.component.html
  frontend/src/app/modules/new-meeting/new-meeting/new-meeting.component.sass
  frontend/src/app/modules/new-meeting/new-meeting/new-meeting.component.ts
  frontend/src/app/modules/settings/user/user-profile-page/user-profile-page.component.html
  frontend/src/app/shared/constants/model-validation.ts
  frontend/src/app/shared/enums/locationType.ts
  frontend/src/app/shared/enums/unitOfTime.ts
  frontend/src/app/shared/material/material.module.ts
Labels: frontend, backend

#195 [#177] fixed external booking page text
  frontend/src/app/modules/external-booking/external-booking-choose-meeting-page/external-booking-choose-meeting-page.component.html
  frontend/src/app/modules/external-booking/external-booking-choose-meeting-page/external-booking-choose-meeting-page.component.sass
Labels: bug, frontend

#194 Delete header tag #187
  frontend/src/app/modules/calendars/calendars-page/calendars-page.component.html
Labels: bug

#191 Fixes #178 Allow user registration form signIn view
  backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/UserService.cs
  frontend/src/app/modules/auth/components/sign-in-form/sign-in-form.component.ts
  frontend/src/app/modules/auth/components/sign-up-form/sign-up-form.component.ts
Labels: bug

#184 Bug/team name left menu #182
  frontend/src/app/modules/side-menu/menu/side-menu.component.html
  frontend/src/app/modules/side-menu/menu/side-menu.component.sass
Labels: bug

#203 [#190] created email notification templates
  frontend/src/app/core/helpers/notification-templates.ts
  frontend/src/app/core/models/INotificationEmail.ts
  frontend/src/app/modules/availability/new-slot/notification-emails/notification-emails.component.ts
Labels: bug, frontend

#211 #168 There is no uniform background
  frontend/src/app/modules/bookings/booker/booker.component.html
  frontend/src/app/modules/bookings/booker/booker.component.sass
  frontend/src/app/modules/bookings/bookers-page/bookers-page.component.html
  frontend/src/app/modules/bookings/bookers-page/bookers-page.component.sass
Labels: bug
